### ISSUE TITLE
Deploy CP4WAIOSP on AWS Cloud with GitOps

### ISSUE THREAD

**Issue by gyliu513** [IBM/cp4waiops-gitops#30] opened 2021-12-08 01:09 UTC
@cloud-pak-gitops/cp4wiops-gitops-core

**Comment by huang-cn** [comment] 2022-04-15 03:01
after deployed aimanager and eventmanger on AWS, the UI says application health.
![image](https://user-images.githubusercontent.com/58250676/163510773-ea20256d-e1b7-48bd-9983-98cb297fb519.png)

But there're lots of pod in pending state.
```
NAMESPACE  NAME                                                         READY  STATUS    RESTARTS  AGE    IP            NODE                                        NOMINATED  NODE    READINESS  GATES
cp4waiops  aiops-ir-analytics-probablecause-6fdf459495-99jjl            0/1    Pending   0         16h    <none>        <none>                                      <none>     <none>
cp4waiops  aiops-ir-analytics-spark-pipeline-composer-7997dd47d6-7dlvf  0/1    Pending   0         16h    <none>        <none>                                      <none>     <none>
cp4waiops  cp4waiops-eventprocessor-eve-29ee-ep-taskmanager-1           0/1    Pending   0         16h    <none>        <none>                                      <none>     <none>
cp4waiops  gateway-kong-config-svc-27499830--1-hnnrr                    0/1    Pending   0         19m    <none>        <none>                                      <none>     <none>
cp4waiops  gateway-kong-config-svc-27499840--1-kbhq4                    0/1    Pending   0         9m20s  <none>        <none>                                      <none>     <none>
noi        evtmanager-cassandra-0                                       0/1    Pending   0         33m    <none>        <none>                                      <none>     <none>
noi        evtmanager-ea-noi-layer-easetupomnibus--1-6mxzw              0/1    Init:0/3  0         34m    10.131.0.249  ip-10-0-251-163.us-east-2.compute.internal  <none>     <none>
noi        evtmanager-impactgui-0                                       0/2    Init:0/1  0         33m    10.131.0.253  ip-10-0-251-163.us-east-2.compute.internal  <none>     <none>
noi        evtmanager-kafka-0                                           0/2    Pending   0         33m    <none>        <none>                                      <none>     <none>
noi        evtmanager-kafka-1                                           0/2    Pending   0         33m    <none>        <none>                                      <none>     <none>
noi        evtmanager-kafka-2                                           0/2    Pending   0         33m    <none>        <none>                                      <none>     <none>
noi        evtmanager-nciserver-0                                       0/2    Pending   0         33m    <none>        <none>                                      <none>     <none>
noi        evtmanager-ncobackup-0                                       0/2    Pending   0         33m    <none>        <none>                                      <none>     <none>
noi        evtmanager-ncoprimary-0                                      0/1    Pending   0         33m    <none>        <none>                                      <none>     <none>
noi        evtmanager-webgui-0                                          0/2    Pending   0         33m    <none>        <none>   
```

The events indicate it caused by Insufficient cpu:
```
Events:
  Type     Reason            Age        From  Message
  ----     ------            ----       ----  -------
  Warning  FailedScheduling  <unknown>        0/9 nodes are available: 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 6 Insufficient cpu.
  Warning  FailedScheduling  <unknown>        0/9 nodes are available: 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 6 Insufficient cpu.
```

But actually there're plenty of CPU available:
```
NAME                                         CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
ip-10-0-140-161.us-east-2.compute.internal   536m         7%     6961Mi          22%
ip-10-0-142-215.us-east-2.compute.internal   1119m        14%    7948Mi          25%
ip-10-0-149-103.us-east-2.compute.internal   1593m        21%    8835Mi          28%
ip-10-0-165-20.us-east-2.compute.internal    1049m        13%    10893Mi         35%
ip-10-0-181-76.us-east-2.compute.internal    2246m        29%    12881Mi         41%
ip-10-0-220-213.us-east-2.compute.internal   491m         6%     11675Mi         37%
ip-10-0-233-74.us-east-2.compute.internal    671m         8%     8053Mi          26%
ip-10-0-251-163.us-east-2.compute.internal   1201m        16%    13211Mi         42%
ip-10-0-255-29.us-east-2.compute.internal    2559m        34%    11990Mi         38%
```

Not sure what happened, still investigating.

**Comment by morningspace** [comment] 2022-04-15 05:49
@huang-cn I think this is the actual cpu usage, while the pods in pending are because they requires more cpu than the actual use, i.e.: the `cpu requests` settings. Also, only 3 nodes (workers) can be allocated for workload deployment.

What are the cpu/mem settings for the three workers that you allocated?

**Comment by huang-cn** [comment] 2022-04-15 11:48
@morningspace that env was actually 3 masters (8C/32G) + 6 workers (8C/32G). and yes, you're right, it turns out it requires more CPU,

**Comment by huang-cn** [comment] 2022-04-15 11:52
now I created a much larger env with 3 masters (8C/32G) + 5 workers (16C/64G), finally I got both ai manager and event manager installed, there's no longer insufficient cpu issue, but there's `post-aiops-update-user-role-bfp76` pod CrashLoopBackOff. the env seems up and running, not sure what the failed pod will affect.

**Comment by morningspace** [comment] 2022-04-15 13:31
What's the kubectl describe output, it looks that is a job, if it's completed, and you do not see errors in events or logs, probably you can rerun it by replacing the completed one, so that you can check pod logs, and describe to check events. @huang-cn

**Comment by huang-cn** [comment] 2022-04-15 15:54
@morningspace I checked the log, there's error indicating problem updating admin role.
``` 
obtained admin role:  {
  RoleInfo: {
    description: 'Administrator role',
    id: 'zen_administrator_role',
    permissions: [
      'administrator',
      'can_provision',
      'waiops_manage_integrations',
      'waiops_view_integrations',
      'waiops_view_operational_data',
      'waiops_view_topologies',
      'waiops_manage_topology_templates',
      'waiops_manage_topology_comments',
      'waiops_manage_applications',
      'waiops_manage_topology_tools',
      'waiops_manage_topology_presentation',
      'waiops_manage_topology_rules',
      'waiops_manage_advanced_topology_settings',
      'waiops_view_aimodels_status',
      'waiops_manage_aimodels',
      'waiops_view_operational_policies',
      'waiops_edit_operational_policies',
      'waiops_delete_operational_policies',
      'secure_tunnel_network',
      'secure_tunnel_port_forwarding',
      'secure_tunnel_connector_install',
      'secure_tunnel_create_template',
      'secure_tunnel_renew_cert',
      'secure_tunnel_view_audit_log',
      'waiops_use_runbooks',
      'waiops_author_runbooks',
      'waiops_manage_runbooks',
      'waiops_administer_runbooks'
    ],
    role_name: 'Administrator'
  },
  _messageCode_: '200',
  message: 'Role details retrieved successfully.'
}
updating admin role...
/opt/ibm/server/setup_admin_role.js:104
      throw new Error(`expected response code 200 but got ${code}`)
      ^

Error: expected response code 200 but got 500
    at ClientRequest.<anonymous> (/opt/ibm/server/setup_admin_role.js:104:13)
    at ClientRequest.emit (events.js:412:35)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by huang-cn** [comment] 2022-04-18 03:45
the update-user-role job failure solved, the job post-aiops-update-user-role now Completed.  
It's unrelated to AWS or gitios. restarting zen-watcher fixed the issue. @gyliu513 @morningspace

**Comment by gyliu513** [comment] 2022-04-18 12:38
>  restarting zen-watcher fixed the issue

Do we need to restart the zen-watcher when install on AWS? Why? If so, we need to open an issue internally to fix

**Comment by huang-cn** [comment] 2022-04-18 13:45
There's an issue opened a while ago and deferred @gyliu513 , https://github.ibm.com/katamari/dev-issue-tracking/issues/24723

**Comment by morningspace** [comment] 2022-07-01 00:55
Can we close this issue since the work has been done? @huang-cn

**Comment by huang-cn** [comment] 2022-07-01 02:53
The work had been done, closing the issue.

**Closed by huang-cn** 2022-07-01 02:53 UTC
